version: '3.8'

services:
  bitcoin-node:
    image: ruimarinho/bitcoin-core:alpine
    container_name: bitcoin-node
    volumes:
      - ./bitcoin-data:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333"
    environment:
      BITCOIN_NETWORK: mainnet